const K={f:"khajana.favorites",r:"khajana.recent",p:"khajana.progress",d:"khajana.dark"};const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)??JSON.stringify(f))}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let favorites=read(K.f,[]),recent=read(K.r,[]),progress=read(K.p,{viewed:0,quizAttempts:0,quizCorrect:0});
function stats(){favoriteCount.textContent=favorites.length;accuracy.textContent=(progress.quizAttempts?Math.round(progress.quizCorrect/progress.quizAttempts*100):0)+"%"}
function lists(){favoritesBox.innerHTML=favorites.length?favorites.map(id=>`<a class="list-link" href="/?wordId=${id}">⭐ Word #${id}</a>`).join(""):"<span class='muted'>No favorites yet.</span>";recentBox.innerHTML=recent.length?recent.map(id=>`<a class="list-link" href="/?wordId=${id}">🕘 Word #${id}</a>`).join(""):"<span class='muted'>No recently viewed words.</span>"}
function favButtons(){document.querySelectorAll(".favorite").forEach(b=>{let id=+b.dataset.id;b.textContent=favorites.includes(id)?"★":"☆";b.onclick=()=>{favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[id,...favorites];write(K.f,favorites);stats();lists();favButtons()}})}
function recentWord(id){recent=[id,...recent.filter(x=>x!==id)].slice(0,20);progress.viewed=(progress.viewed||0)+1;write(K.r,recent);write(K.p,progress);lists()}
function speak(w){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(w);u.lang="en-US";u.rate=.82;speechSynthesis.speak(u)}
function theme(){let d=localStorage.getItem(K.d)==="true";document.body.classList.toggle("dark-mode",d);themeButton.textContent=d?"☀️ Light":"🌙 Dark"}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function quiz(){quizModal.style.display="flex";quizBody.innerHTML="Loading...";let qs=await(await fetch("/api/quiz?count=10")).json(),i=0,score=0;function render(){if(i>=qs.length){quizBody.innerHTML=`<div style="text-align:center"><h2>🎉 Score: ${score}/${qs.length}</h2><p>Progress saved locally.</p><button id="restartQuiz">Try Again</button></div>`;restartQuiz.onclick=quiz;return}let q=qs[i];quizBody.innerHTML=`<p class="muted">Question ${i+1} of ${qs.length}</p><h2>${esc(q.word)}</h2><div>${q.options.map((o,n)=>`<button class="quiz-option" data-i="${n}">${esc(o)}</button>`).join("")}</div>`;document.querySelectorAll(".quiz-option").forEach(b=>b.onclick=()=>{let selected=q.options[+b.dataset.i];progress.quizAttempts++;if(selected===q.meaning){score++;progress.quizCorrect++;b.classList.add("correct")}else b.classList.add("wrong");write(K.p,progress);stats();setTimeout(()=>{i++;render()},350)})}render()}
document.addEventListener("DOMContentLoaded",()=>{theme();stats();lists();favButtons();themeButton.onclick=()=>{localStorage.setItem(K.d,String(!document.body.classList.contains("dark-mode")));theme()};document.querySelectorAll(".speak-button").forEach(b=>b.onclick=()=>speak(b.dataset.word));document.querySelectorAll(".word-card").forEach(c=>c.addEventListener("focus",()=>recentWord(+c.dataset.id)));randomButton.onclick=async()=>{let w=await(await fetch("/api/random")).json();location.href=`/?wordId=${w.id}`};quizButton.onclick=quiz;closeQuiz.onclick=()=>quizModal.style.display="none";document.addEventListener("keydown",e=>{if(e.key==="Escape"){quizModal.style.display="none";search?.focus()}if(e.key==="ArrowDown"&&document.activeElement?.id==="search"){e.preventDefault();document.querySelector(".word-card")?.focus()}if((e.key==="Enter"||e.key===" ")&&document.activeElement?.classList.contains("word-card")){e.preventDefault();location.href=`/?wordId=${document.activeElement.dataset.id}`}})});