<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Khajana JSP</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/app.css">
<style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f8fafc;color:#0f172a}.container{width:min(1200px,calc(100% - 32px));margin:auto}header{position:sticky;top:0;z-index:20;background:#fff;border-bottom:1px solid #e2e8f0}.head{display:flex;justify-content:space-between;align-items:center;padding:18px 0}main{padding:28px 0}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:20px}.layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:20px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}input,select,button,.button{border:1px solid #cbd5e1;border-radius:10px;padding:10px 13px;font-size:14px;background:#fff;color:inherit}.search{flex:1;min-width:220px}.primary{background:#4f46e5;color:#fff}.green{background:#059669;color:#fff}.purple{background:#7c3aed;color:#fff}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.wordhead{display:flex;justify-content:space-between}.wordlink{color:inherit;text-decoration:none}.wordlink:hover{color:#4f46e5}.meanings{padding-left:20px;line-height:1.6}.example{border-left:3px solid #818cf8;padding-left:10px;margin-top:12px;color:#64748b;font-style:italic}.wod{background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff}.wod .muted{color:#ddd}.sectionhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}@media(max-width:1000px){.cards{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}}@media(max-width:700px){.stats,.cards{grid-template-columns:1fr}}
</style></head><body>
<header><div class="container head"><div><h1>📚 Khajana</h1><span class="muted">Spring Boot MVC + JSP</span></div><button id="themeButton">🌙 Dark</button></div></header>
<main class="container">
<div class="stats"><div class="card"><span class="muted">Total words</span><div class="stat-value">${allCount}</div></div><div class="card"><span class="muted">Results</span><div class="stat-value">${resultCount}</div></div><div class="card"><span class="muted">Favorites</span><div id="favoriteCount" class="stat-value">0</div></div><div class="card"><span class="muted">Quiz accuracy</span><div id="accuracy" class="stat-value">0%</div></div></div>
<div class="layout"><section>
<form method="get" action="${pageContext.request.contextPath}/" class="card" style="margin-bottom:20px"><div class="toolbar">
<input id="search" class="search" name="q" value="<c:out value='${q}'/>" placeholder="Search word, meaning or example..." autofocus>
<select name="type"><option value="">All parts of speech</option><c:forEach var="t" items="${types}"><option value="<c:out value='${t}'/>" <c:if test="${t.equalsIgnoreCase(selectedType)}">selected</c:if>><c:out value="${t}"/></option></c:forEach></select><input type="hidden" name="size" value="${size}"><button class="primary">Search</button></div></form>
<div class="sectionhead"><h2>Vocabulary</h2><div class="toolbar"><a class="button" href="${pageContext.request.contextPath}/">Reset</a><button id="randomButton" class="green">🎲 Random</button><button id="quizButton" class="purple">🧠 Quiz</button></div></div>
<div class="cards"><c:forEach var="w" items="${words}"><article class="card word-card" tabindex="0" data-id="${w.id}">
<div class="wordhead"><div><h2><a class="wordlink" href="${pageContext.request.contextPath}/?wordId=${w.id}"><c:out value="${w.word}"/></a></h2><span class="badge"><c:out value="${w.type}"/></span></div><button class="favorite" data-id="${w.id}">☆</button></div>
<ul class="meanings"><c:forEach var="m" items="${w.meanings}"><li><c:out value="${m}"/></li></c:forEach></ul>
<c:if test="${not empty w.examples}"><div class="example"><c:out value="${w.examples[0]}"/></div></c:if>
<div style="text-align:right;margin-top:14px"><button class="speak-button" data-word="<c:out value='${w.word}'/>">🔊 Pronounce</button></div>
</article></c:forEach></div>
<c:if test="${empty words}"><div class="card" style="text-align:center;margin-top:20px">🔎<p>No words found.</p></div></c:if>
<c:if test="${totalPages>1}"><div class="pagination" style="text-align:center;margin-top:22px"><c:if test="${page>1}"><a href="${pageContext.request.contextPath}/?q=${q}&type=${selectedType}&page=${page-1}&size=${size}">← Previous</a></c:if><span>${page} / ${totalPages}</span><c:if test="${page<totalPages}"><a href="${pageContext.request.contextPath}/?q=${q}&type=${selectedType}&page=${page+1}&size=${size}">Next →</a></c:if></div></c:if>
</section>
<aside><section class="card wod"><span class="muted">WORD OF THE DAY</span><h2><c:out value="${wordOfDay.word}"/></h2><span class="badge"><c:out value="${wordOfDay.type}"/></span><ul class="meanings"><c:forEach var="m" items="${wordOfDay.meanings}"><li><c:out value="${m}"/></li></c:forEach></ul><a class="button" href="${pageContext.request.contextPath}/?wordId=${wordOfDay.id}">Open word</a></section>
<c:if test="${not empty selected}"><section class="card" style="margin-top:20px"><span class="muted">SELECTED WORD</span><h2><c:out value="${selected.word}"/></h2><span class="badge"><c:out value="${selected.type}"/></span><h3>Meanings</h3><ul class="meanings"><c:forEach var="m" items="${selected.meanings}"><li><c:out value="${m}"/></li></c:forEach></ul><c:if test="${not empty selected.examples}"><h3>Examples</h3><c:forEach var="e" items="${selected.examples}"><div class="example"><c:out value="${e}"/></div></c:forEach></c:if><button class="speak-button" data-word="<c:out value='${selected.word}'/>">🔊 Pronounce</button></section></c:if>
<section class="card" style="margin-top:20px"><h3>⭐ Favorites</h3><div id="favorites"><span class="muted">No favorites yet.</span></div></section>
<section class="card" style="margin-top:20px"><h3>🕘 Recently viewed</h3><div id="recent"><span class="muted">No recently viewed words.</span></div></section>
</aside></div></main>
<div id="quizModal"><div id="quizPanel" class="card"><div class="sectionhead"><h2>🧠 Vocabulary Quiz</h2><button id="closeQuiz">×</button></div><div id="quizBody"></div></div></div>
<script src="${pageContext.request.contextPath}/js/app.js"></script></body></html>